language: csharp
dist: trusty
solution: Fabulosa.sln
dotnet: 2.1.302
mono: latest
install:
  - mono .paket/paket.exe install
script:
  - bash ./fake.sh build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: output/  # or remove this line to upload from root of repo
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  on:
    branch: master